sudo: false
os:
  - linux
  - osx
language: node_js
install:
  - pushd preliminaries && npm install -d && popd
  - pushd preliminaries-parser-toml && npm install -d && popd
script: 
  - pushd preliminaries && npm test && popd
  - pushd preliminaries-parser-toml && npm test && popd
node_js:
  - node
  - '6'
  - '4'
  - '0.12'
  - '0.10'
matrix:
  allow_failures:
    - node_js: '4'
    - node_js: '0.12'
    - node_js: '0.10'
