sudo: false
os:
  - linux
  - osx
language: node_js
install: make install
script: make all
node_js:
  - node
  - '6'
  - '4'
  - '0.12'
  - '0.10'
matrix:
  allow_failures:
    - node_js: '4'
    - node_js: '0.12'
    - node_js: '0.10'
